name: Playwright Tests

on:
  deployment_status:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.deployment.environment || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "22.x"
  PNPM_VERSION: 10.9.0

jobs:
  test:
    name: "Playwright Tests"
    environment: preview
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' }}
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install system dependencies for canvas
        run: sudo apt-get update && sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev libpixman-1-dev

      - name: Install dependencies
        run: pnpm install:web

      - name: Install Vercel CLI
        run: pnpm install -g vercel@latest

      - name: Install Playwright browsers
        run: pnpm --filter web exec playwright install chromium

      - name: Get Vercel Preview URL
        if: ${{ github.event_name == 'deployment_status' }}
        run: |
          echo "PLAYWRIGHT_TEST_BASE_URL=${{ github.event.deployment_status.target_url }}" >> $GITHUB_ENV
          echo "Testing against Vercel Preview URL: ${{ github.event.deployment_status.target_url }}"

      - name: Run Playwright tests
        run: pnpm test:e2e
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ env.PLAYWRIGHT_TEST_BASE_URL }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: apps/web/playwright-report/
          retention-days: 30

      - name: Deploy playwright report to Vercel and capture URL
        if: always()
        id: deploy_report
        run: |
          cd apps/web/playwright-report
          vercel link --project janet-playwright --yes --token=${{ secrets.VERCEL_TOKEN }}
          DEPLOY_URL=$(vercel deploy --yes --token=${{ secrets.VERCEL_TOKEN }} | tail -n 1)
          if [[ "$DEPLOY_URL" == http* ]]; then
            echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV
            echo "Report URL: $DEPLOY_URL"
          else
            echo "Failed to capture valid deployment URL."
          fi
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Add/Update Playwright Report Comment on PR
        # Only run if triggered by deployment_status and a deploy URL was captured
        if: always() && github.event_name == 'deployment_status' && env.DEPLOY_URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          COMMIT_SHA: ${{ github.event.deployment.sha }}
        run: |
          chmod +x .github/scripts/comment-playwright-report.sh # Ensure script is executable
          ./.github/scripts/comment-playwright-report.sh \
            "$COMMIT_SHA" \
            "${{ env.DEPLOY_URL }}" \
            "$GH_REPO"
